### PR TITLE
Fix errors in Firefox

### PR DESCRIPTION
**Pull request by keyserfaty**
- Fix style errors in Firefox and in bigger resolutions.
- Fix the order of the fetching of dependencies to fix an error that occurred sometimes.
- Uglify the js written in the index html to reduce the size of the file (you can find the full code in a previous commit).
- Fix build script in the `package.json`.

### CODE REVIEW

**Comment by andrewxhill** [comment]
amazing! taking a look now.

**Comment by andrewxhill** [comment]
Looks great! Only one thing I'm seeing on mobile, iPhone SE so fairly narrow screen. For some reason the final subscribe button is losing the styles,

img_7bf8d939c718-1

**Comment by keyserfaty** [comment]
Hm, that's weird. Is it in Chrome or Safari? I'll have a look.

**Comment by keyserfaty** [comment]
We were able to reproduce the bug running the site from Xcode so I'll be taking a look at it and get back to you when we have a solution.

**Comment by andrewxhill** [comment]
awesome. yeah, it was firefox for me.

**Pull request merged**
